Add option to configure layer for control center window
ErikReider/SwayNotificationCenter pull request #175
Opened 2022-10-18 19:21 UTC by junglerobba

Hi!

This adds a config option to configure the layer_shell layer, ie the rules for above/below which windows the control center will appear. This is mostly for overlay so it can appear above fullscreen windows, I doubt background and bottom are useful really, but they're there, so why not expose them :shrug:

2022-10-19 07:06 UTC, ErikReider requested changes

2022-10-19 07:06 UTC, ErikReider commented on src/configModel/configModel.vala
> +        }
`BOTTOM` is missing

2022-10-19 16:23 UTC, junglerobba commented on src/configModel/configModel.vala
> +        }
Yep, somehow missed this

2022-10-20 21:58 UTC, ErikReider approved these changes
LGTM! I really appreciate the help! :)

2022-10-20 22:01 UTC, merged