Add example i3status-rs config to README.md
ErikReider/SwayNotificationCenter pull request #202
Opened 2023-01-19 02:44 UTC by bim9262

I just added a swaync driver to i3status-rs and just wanted to share an example config.

2023-01-19 18:22 UTC, ErikReider commented
I didn't even know that i3status worked with wlroots WMs

2023-01-19 18:25 UTC, ErikReider commented
Oh, you're referring to i3status and not i3bar... My bad 😅

2023-01-19 18:42 UTC, ErikReider requested changes
Other than that, LGTM! :)

2023-01-19 18:42 UTC, ErikReider commented on README.md
> +```
Place this below the Waybar example due to it being more popular

2023-01-19 18:46 UTC, ErikReider approved these changes
> I just added a swaync driver to i3status-rs

Oh wait, you actually added it into i3status?! LGTM. Thanks for the help ❤️

2023-01-19 18:46 UTC, merged

2023-01-20 00:04 UTC, bim9262 commented
I did (well i3status-rs)! You're welcome :smile: