Menu animation
ErikReider/SwayNotificationCenter pull request #230
Opened 2023-03-03 18:05 UTC by JannisPetschenka

Small changes to the menubar to add some animation :)

2023-03-03 18:12 UTC, ErikReider commented
I'll look at this tomorrow. Ping me if I forget :)

2023-03-04 18:33 UTC, ErikReider requested changes
LGTM otherwise! :)

2023-03-04 18:33 UTC, ErikReider commented on src/configSchema.json
> +							"enum": ["slide_down", "slide_up", "none"]
Wrong indent type

2023-03-04 18:33 UTC, ErikReider commented on src/controlCenter/widgets/menubar/menubar.vala
> +                    case "none":
Put default here to simplify

2023-03-04 18:33 UTC, ErikReider commented on src/controlCenter/widgets/menubar/menubar.vala
>                      menu.get_style_context ().add_class (obj.name);
Forgot to mention this before, we should avoid setting the class of the menu and the buttons if the `obj.name` is null. My bad 😅

2023-03-04 18:33 UTC, ErikReider commented on src/controlCenter/widgets/menubar/menubar.vala
>                  });
Indent this. This is a really annoying Uncrustify issue that I've not been able to solve yet...

2023-03-04 18:33 UTC, ErikReider commented on src/controlCenter/widgets/menubar/menubar.vala
> +        Gtk.RevealerTransitionType ? animation_type;
Remove the question mark. Shouldn't be nullable

2023-03-04 20:18 UTC, ErikReider commented
Oh yeah, also forgot to mention that there's a weird graphical issue when opening two menus. Looks like the 2nd menu opens over the first one. I'm not sure if that's due to them expanding/contracting at the same time resulting in that behavior or not. Just letting you know :)

2023-03-05 15:24 UTC, JannisPetschenka commented
> Oh yeah, also forgot to mention that there's a weird graphical issue when opening two menus. Looks like the 2nd menu opens over the first one. I'm not sure if that's due to them expanding/contracting at the same time resulting in that behavior or not. Just letting you know :)

Yeah, I'm aware of that issue :) The only way to fix this I can think of is to somehow wait for `animation_duration` ms after closing the boxes before opening the correct one. But that would double the time it takes to open a drop-down :upside_down_face:.. So I thought about just calling it a feature rather than a bug :laughing: But I can look into changing it if you prefer :)

2023-03-05 15:48 UTC, ErikReider approved these changes

2023-03-05 15:48 UTC, merged

2023-03-05 15:54 UTC, ErikReider commented
Thanks again for your help! :)