Per app volume control
ErikReider/SwayNotificationCenter pull request #235
Opened 2023-03-19 16:13 UTC by JannisPetschenka

Haven't tested everything yet, but apart from that should be ready :)

2023-03-28 09:53 UTC, ErikReider commented
I'll try to get to this tonight. If not, ping me :)

2023-03-28 15:39 UTC, ErikReider requested changes
Sorry for the delay. Finally had some free time after "finishing" blur work in SwayFX :)

2023-03-28 15:39 UTC, ErikReider commented on src/controlCenter/widgets/volume/volume.vala
> +        }
Seems like this one isn't working. None of the sink-inputs get removed when ex closing and opening Spotify.

![image](https://user-images.githubusercontent.com/35975961/228291007-ac989873-d63f-4db3-a96c-93ab1eaffc92.png)

2023-03-28 16:02 UTC, JannisPetschenka commented
> Sorry for the delay. Finally had some free time after "finishing" blur work in SwayFX :)

No worries :smile: I'm aware of the issue with deleting elements. The reason is that I close the client when the cc is closed. And since the `remove_active_sink` signal is only send while the client is active, the remove function is never called....

To solve this I could either never close the client or always update the active sinks when opening the cc... But solutions seem sub-optimal to me. I'll see if I can find a better way :)

2023-03-28 16:05 UTC, ErikReider commented
> or always update the active sinks when opening the cc... But solutions seem sub-optimal to me.

If there's no other way, this would be the more optimal solution :)

2023-03-31 16:22 UTC, JannisPetschenka commented
Finally found the time to look into it again :) Should work now :smile: 
Currently if there are no active sink_inputs you can still reveal the levels_listbox and it will just show an empty list... Might change that but apart from that it should be ready :)

2023-04-01 20:07 UTC, ErikReider requested changes

2023-04-01 20:07 UTC, ErikReider commented on src/controlCenter/widgets/volume/pulseSinkInput.vala
> +                sink_input.application_icon_name ?? "application-c-executable",
Use `"application-x-executable"` instead

2023-04-01 20:07 UTC, ErikReider commented on src/controlCenter/widgets/volume/pulseSinkInput.vala
> +    public class SinkInputRow : Gtk.ListBoxRow {
Move class into its own file

2023-04-07 13:41 UTC, JannisPetschenka commented
Fixed the issues and added a label to be displayed when the list of active sink inputs is empty :) Should be ready now :smile:

2023-04-10 21:14 UTC, ErikReider commented
Probably just a line ending issue

2023-04-11 08:31 UTC, ErikReider approved these changes
LGTM! Thanks again for all of the help :)

2023-04-11 08:31 UTC, merged