Fix brightness slider choppiness
ErikReider/SwayNotificationCenter pull request #372
Opened 2024-01-09 04:18 UTC by AmirDahan

Make setting the brightness function async to prevent stutter on some devices.

This probably doesn't happen on a lot of devices but i found it weird that it happens on one of my devices,
This pr should help resolve it.

2024-02-10 14:17 UTC, ErikReider requested changes

2024-02-10 14:17 UTC, ErikReider commented on src/controlCenter/widgets/backlight/backlightUtil.vala
> +        public async void set_brightness (float percent) {
You have to change the call to the methods to include a `.begin` (`implicit .begin is deprecated`)

2024-02-10 16:39 UTC, AmirDahan commented
That should do it

2024-03-06 14:14 UTC, AmirDahan commented
Any updates on this?

2024-03-07 18:44 UTC, merged